# Generated by Django 5.1.7 on 2025-03-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studypal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Growing', 'Growing'), ('Elite', 'Elite')], max_length=10),
        ),
    ]
