# Generated by Django 5.1.7 on 2025-03-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studypal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
