# Generated by Django 5.1.7 on 2025-03-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studypal', '0002_alter_customuser_gender_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='course_of_study',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='student_id',
            new_name='matricNumber',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='user_type',
            new_name='role',
        ),
    ]
